server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/events/**
        - id: registration-service
          uri: lb://registration-service
          predicates:
            - Path=/registration/**

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
